export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const COLLECTION_ROUTE = '/'
export const MYCOLLECTION_ROUTE = '/mycollection'
export const USERS_ROUTE = '/users'